# 使用官方 Node.js 镜像作为基础镜像
FROM node:16-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json
COPY server/package*.json ./

# 安装依赖
RUN npm install

# 复制源代码
COPY server .

# 暴露端口
EXPOSE 3331

# 启动命令
CMD ["node", "index.js"]
